name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies', 'refactor']
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels: ['skip-changelog']
replacers: []
template: |
  ## What’s Changed
  $CHANGES

  ## Deployment Notes
  - Run DB migrations: `php bws/scripts/migrate.php`
  - Set/verify environment variables per `bws/.env.example`
