name: Deploy to HostGator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "database/" \
            --exclude "scripts/" \
            --exclude ".env" \
            ./bws2/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SERVER_WEB_DIR }}/

      - name: Run DB migrations on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_WEB_DIR }}
            ${{ secrets.SERVER_PHP }} bws2/scripts/migrate.php
